import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class FormCadFoto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadFoto.class.getName());

    private Foto foto = new Foto();
    private BDMidia gm = BDMidia.geraBDMidia();
    
    private static FormCadFoto cadFotoUnico;
    
    private FormCadFoto() {
        initComponents();
    }
    
    // METODO SINGLETON
    public static FormCadFoto geraCadFoto(){
        if(cadFotoUnico == null){
            cadFotoUnico = new FormCadFoto();
        }
        return cadFotoUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotID = new javax.swing.JLabel();
        rotTitulo = new javax.swing.JLabel();
        rotExtensao = new javax.swing.JLabel();
        rotTamArq = new javax.swing.JLabel();
        rotDataCriacao = new javax.swing.JLabel();
        rotAltPx = new javax.swing.JLabel();
        rotLargPx = new javax.swing.JLabel();
        rotModelCam = new javax.swing.JLabel();
        cxId = new javax.swing.JTextField();
        cxTitulo = new javax.swing.JTextField();
        cxExtensao = new javax.swing.JTextField();
        cxTamArq = new javax.swing.JTextField();
        cxDataCriacao = new javax.swing.JTextField();
        cxAltPx = new javax.swing.JTextField();
        cxLargPx = new javax.swing.JTextField();
        cxModelCam = new javax.swing.JTextField();
        btInserirMidia = new javax.swing.JButton();
        btAtualizaFoto = new javax.swing.JButton();
        btConsFoto = new javax.swing.JButton();
        btRemoveMidia = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        scrollTabFoto = new javax.swing.JScrollPane();
        tabFoto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Foto");

        rotID.setText("ID:");

        rotTitulo.setText("Titulo:");

        rotExtensao.setText("Extensao:");

        rotTamArq.setText("Tamanho do Arquivo:");

        rotDataCriacao.setText("Data de Criacao:");

        rotAltPx.setText("Altura pixels (px):");

        rotLargPx.setText("Largura pixels (px):");

        rotModelCam.setText("Modelo da Camera:");

        btInserirMidia.setText("Inserir");
        btInserirMidia.addActionListener(this::btInserirMidiaActionPerformed);

        btAtualizaFoto.setText("Atualizar Foto");
        btAtualizaFoto.addActionListener(this::btAtualizaFotoActionPerformed);

        btConsFoto.setText("Consultar Foto");
        btConsFoto.addActionListener(this::btConsFotoActionPerformed);

        btRemoveMidia.setText("Remover Midia");
        btRemoveMidia.addActionListener(this::btRemoveMidiaActionPerformed);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(this::btLimparActionPerformed);

        btSair.setText("Sair");
        btSair.addActionListener(this::btSairActionPerformed);

        tabFoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Extensao", "Modelo", "Data", "MP"
            }
        ));
        tabFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFotoMouseClicked(evt);
            }
        });
        scrollTabFoto.setViewportView(tabFoto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSair))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(scrollTabFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btInserirMidia)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btAtualizaFoto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btConsFoto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btRemoveMidia))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotTamArq, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cxExtensao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(cxTitulo, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(cxId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(cxTamArq, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rotAltPx, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rotLargPx, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rotModelCam, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cxAltPx, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cxLargPx)
                                    .addComponent(cxModelCam)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rotDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cxDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotID)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotDataCriacao)
                    .addComponent(cxDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotAltPx)
                            .addComponent(cxAltPx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotLargPx)
                            .addComponent(cxLargPx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotModelCam)
                            .addComponent(cxModelCam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotTitulo)
                            .addComponent(cxTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotExtensao)
                            .addComponent(cxExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotTamArq)
                            .addComponent(cxTamArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserirMidia)
                    .addComponent(btAtualizaFoto)
                    .addComponent(btConsFoto)
                    .addComponent(btRemoveMidia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTabFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                  
    private void btInserirMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirMidiaActionPerformed
        insMidia();
        constTab();
    }//GEN-LAST:event_btInserirMidiaActionPerformed

    private void btAtualizaFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaFotoActionPerformed
        atualizaFoto();
        constTab();
    }//GEN-LAST:event_btAtualizaFotoActionPerformed

    private void btConsFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsFotoActionPerformed
        consFotoId();
    }//GEN-LAST:event_btConsFotoActionPerformed

    private void btRemoveMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveMidiaActionPerformed
        removeMidiaId();
        constTab();
    }//GEN-LAST:event_btRemoveMidiaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void tabFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFotoMouseClicked
        selectTabFoto();
    }//GEN-LAST:event_tabFotoMouseClicked

    
    public void limpar(){
        cxId.setText("");
        cxTitulo.setText("");
        cxExtensao.setText("");
        cxTamArq.setText("");
        cxDataCriacao.setText("");
        cxAltPx.setText("");
        cxLargPx.setText("");
        cxModelCam.setText("");
        cxId.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            dispose();
        }
    }
    
    public void selectTabFoto(){
        String valLin = "";
        int posLin = tabFoto.getSelectedRow();
        
        for(int col = 0; col < tabFoto.getColumnCount(); col++){
            valLin += tabFoto.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tabFoto.getColumnCount()){
                valLin += " -  ";
            }
        }
        JOptionPane.showMessageDialog(
            this,
            "Midia selecionada:\n" + valLin,
            "Seleção em Tabela",
            1
        );
    }
    
    public void constTab(){
        DefaultTableModel modelTab = (DefaultTableModel) tabFoto.getModel();
        int posLin = 0;
        modelTab.setRowCount(posLin);
        
        for(Foto f : gm.getBdFoto()){
            modelTab.insertRow(posLin, new Object[]{
                f.getId(), f.getTitulo(), f.getArquivo().getExtensao(), 
                f.getModeloCamera(), f.getArquivo().getDataCriacao(), 
                String.format("%.2f", Double.valueOf(f.calcularMegapixel()))
            });
            posLin++;
        }
    }
    
    public void insMidia(){
        foto = new Foto();
        int erro = 0;
        
        try {
            foto.setId(Integer.parseInt(cxId.getText()));
            foto.setTitulo(cxTitulo.getText());
            foto.getArquivo().setExtensao(cxExtensao.getText()); 
            foto.getArquivo().setTamanhoArquivo(Float.parseFloat(cxTamArq.getText())); 
            foto.getArquivo().setDataCriacao(cxDataCriacao.getText()); 
            foto.setAlturaPixel(Integer.parseInt(cxAltPx.getText()));
            foto.setLarguraPixel(Integer.parseInt(cxLargPx.getText()));
            foto.setModeloCamera(cxModelCam.getText()); 
            
            if(erro == 0 && foto.getId() > 0){
                foto = gm.insMidia(foto);
            } else {
                foto = null;
            }
        
            if(foto != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Foto inserida com sucesso!",
                    "Inserir Foto",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel inserir: Ja existe uma foto com esse ID",
                    "Inserir Foto",
                    JOptionPane.ERROR_MESSAGE   
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }
        catch(TamanhoInvalidoException tie){
            JOptionPane.showMessageDialog(
                this,
                "O tamanho do arquivo deve ser maior que 0 MB",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxTamArq.setText("");
            cxTamArq.requestFocus();
            erro = 1;
        }
        
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "Os campos ID, Tamanho, Altura e Largura devem conter apenas numeros",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
        
    }
    
    public void atualizaFoto(){
        foto = new Foto();
        int erro = 0;
        
        try{
            foto.setId(Integer.parseInt(cxId.getText()));
            foto.setTitulo(cxTitulo.getText());
            foto.getArquivo().setExtensao(cxExtensao.getText()); 
            foto.getArquivo().setTamanhoArquivo(Float.parseFloat(cxTamArq.getText())); 
            foto.getArquivo().setDataCriacao(cxDataCriacao.getText()); 
            foto.setAlturaPixel(Integer.parseInt(cxAltPx.getText()));
            foto.setLarguraPixel(Integer.parseInt(cxLargPx.getText()));
            foto.setModeloCamera(cxModelCam.getText()); 
        }
        catch(TamanhoInvalidoException tie){
            JOptionPane.showMessageDialog(
                this,
                "O tamanho do arquivo deve ser maior que 0 MB",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxTamArq.setText("");
            cxTamArq.requestFocus();
            erro = 1;
        }
    
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "Os campos ID, Tamanho, Altura e Largura devem conter apenas numeros",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
        
        if(erro == 0){
            Foto atualizado = gm.atualizaMidia(foto);
            if(atualizado != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Foto atualizada com sucesso. Verifique os Dados",
                    "Atualização de Midia",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel atualizar: Nao existe uma foto com este ID",
                    "Atualização de Midia",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        } 
    }
    
    public void consFotoId(){
        foto = new Foto();
        try{
            foto.setId(Integer.parseInt(cxId.getText()));
            
            foto = gm.consMidiaId(foto);
            
            if(foto != null){
                cxId.setText(Integer.toString(foto.getId()));
                cxTitulo.setText(foto.getTitulo());
                cxExtensao.setText(foto.getArquivo().getExtensao()); 
                cxTamArq.setText(Float.toString(foto.getArquivo().getTamanhoArquivo())); 
                cxDataCriacao.setText(foto.getArquivo().getDataCriacao()); 
                cxAltPx.setText(Integer.toString(foto.getAlturaPixel()));
                cxLargPx.setText(Integer.toString(foto.getLarguraPixel()));
                cxModelCam.setText(foto.getModeloCamera());
                
                JOptionPane.showMessageDialog(
                    this,
                    "Foto encontrada. Verifique os Dados",
                    "Consulta de Foto",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
            else{
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel realizar a consulta: ID nao encontrado",
                    "Consulta de Foto",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }

        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "A entrada de dados deve ser numero",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
        } 
    }
    
    public void removeMidiaId(){
        foto = new Foto();
        int erro = 0;
        
        try{
            foto.setId(Integer.parseInt(cxId.getText()));
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "A entrada de dados deve ser numero",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
        
        if(erro == 0){
            Foto removido = gm.removeMidiaId(foto);
            
            if(removido != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Foto removida com sucesso",
                    "Remover Midia",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel remover: ID nao encontrado",
                    "Remover Midia",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadFoto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizaFoto;
    private javax.swing.JButton btConsFoto;
    private javax.swing.JButton btInserirMidia;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemoveMidia;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAltPx;
    private javax.swing.JTextField cxDataCriacao;
    private javax.swing.JTextField cxExtensao;
    private javax.swing.JTextField cxId;
    private javax.swing.JTextField cxLargPx;
    private javax.swing.JTextField cxModelCam;
    private javax.swing.JTextField cxTamArq;
    private javax.swing.JTextField cxTitulo;
    private javax.swing.JLabel rotAltPx;
    private javax.swing.JLabel rotDataCriacao;
    private javax.swing.JLabel rotExtensao;
    private javax.swing.JLabel rotID;
    private javax.swing.JLabel rotLargPx;
    private javax.swing.JLabel rotModelCam;
    private javax.swing.JLabel rotTamArq;
    private javax.swing.JLabel rotTitulo;
    private javax.swing.JScrollPane scrollTabFoto;
    private javax.swing.JTable tabFoto;
    // End of variables declaration//GEN-END:variables
}
