import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class FormRelGerMidia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormRelGerMidia.class.getName());

    private BDMidia gm = BDMidia.geraBDMidia();
    private static FormRelGerMidia relatGeralUnico;
    
    private FormRelGerMidia() {
        initComponents();
    }
    
    // METODO SINGLETON
    public static FormRelGerMidia geraRelatGeral(){
        if(relatGeralUnico == null){
            relatGeralUnico = new FormRelGerMidia();
        }
        return relatGeralUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotRelGelMidia = new javax.swing.JLabel();
        rotConsulta = new javax.swing.JLabel();
        rotFoto = new javax.swing.JLabel();
        rotMusica = new javax.swing.JLabel();
        rotVideo = new javax.swing.JLabel();
        cxData = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        btMostrarTudo = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        scrollTabFoto = new javax.swing.JScrollPane();
        tabFoto = new javax.swing.JTable();
        scrollTabMusica = new javax.swing.JScrollPane();
        tabMusica = new javax.swing.JTable();
        scrollTabVideo = new javax.swing.JScrollPane();
        tabVideo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorio Geral de Midias");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        rotRelGelMidia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rotRelGelMidia.setText("Relatorio Geral de Midias:");

        rotConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotConsulta.setText("Consulta por Data de Criacao:");

        rotFoto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotFoto.setText("Foto:");

        rotMusica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotMusica.setText("Musica:");

        rotVideo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rotVideo.setText("Video:");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(this::btPesquisarActionPerformed);

        btMostrarTudo.setText("Mostrar Tudo");
        btMostrarTudo.addActionListener(this::btMostrarTudoActionPerformed);

        btSair.setText("Sair");
        btSair.addActionListener(this::btSairActionPerformed);

        tabFoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Extensao", "Tamanho", "Data", "AlturaPx", "LarguraPx", "Modelo", "MP"
            }
        ));
        tabFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFotoMouseClicked(evt);
            }
        });
        scrollTabFoto.setViewportView(tabFoto);

        tabMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Duracao", "Extensao", "Tamanho", "Data", "Artista", "Album", "Genero"
            }
        ));
        tabMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMusicaMouseClicked(evt);
            }
        });
        scrollTabMusica.setViewportView(tabMusica);

        tabVideo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Duracao", "Extensao", "Tamanho", "Data", "Qualidade", "FPS", "Codec", "MP"
            }
        ));
        tabVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVideoMouseClicked(evt);
            }
        });
        scrollTabVideo.setViewportView(tabVideo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotRelGelMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rotConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMostrarTudo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSair)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollTabVideo)
                            .addComponent(scrollTabMusica)
                            .addComponent(scrollTabFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rotRelGelMidia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar)
                    .addComponent(btMostrarTudo)
                    .addComponent(btSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rotFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotVideo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rotMusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTabMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        constTabFoto();
        constTabMusica();
        constTabVideo();
    }//GEN-LAST:event_formWindowActivated

    private void tabFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFotoMouseClicked
        selectTabFoto();
    }//GEN-LAST:event_tabFotoMouseClicked

    private void tabMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMusicaMouseClicked
        selectTabMusica();
    }//GEN-LAST:event_tabMusicaMouseClicked

    private void tabVideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVideoMouseClicked
        selectTabVideo();
    }//GEN-LAST:event_tabVideoMouseClicked

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        pesquisaData();
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btMostrarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMostrarTudoActionPerformed
        constTabFoto();
        constTabMusica();
        constTabVideo();
        cxData.setText("");
    }//GEN-LAST:event_btMostrarTudoActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            dispose();
        }
    }
    
    public void pesquisaData(){

    String data = cxData.getText().trim();

    DefaultTableModel modelFoto = (DefaultTableModel) tabFoto.getModel();
    DefaultTableModel modelMus = (DefaultTableModel) tabMusica.getModel();
    DefaultTableModel modelVid = (DefaultTableModel) tabVideo.getModel();
    int posFoto = 0;
    int posMus = 0;
    int posVid = 0;

    modelFoto.setRowCount(posFoto);
    modelMus.setRowCount(posMus);
    modelVid.setRowCount(posVid);
    
    for(Foto f : gm.getBdFoto()){
        if(f.getArquivo().getDataCriacao().equals(data)){
            modelFoto.insertRow(posFoto, new Object[]{
                f.getId(), f.getTitulo(), f.getArquivo().getExtensao(), 
                f.getArquivo().getTamanhoArquivo(), f.getArquivo().getDataCriacao(),
                f.getAlturaPixel(), f.getLarguraPixel(), f.getModeloCamera(), 
                String.format("%.2f", Double.valueOf(f.calcularMegapixel()))
            });
            posFoto++;
        }
    }

    for(Musica m : gm.getBdMusica()){
        if(m.getArquivo().getDataCriacao().equals(data)){
            modelMus.insertRow(posMus, new Object[]{
                m.getId(), m.getTitulo(), m.getDuracao(), m.getArquivo().getExtensao(), 
                m.getArquivo().getTamanhoArquivo(), m.getArquivo().getDataCriacao(), 
                m.getArtista(), m.getAlbum(), m.getGenero()
            });
            posMus++;
        }
    }

    for(Video v : gm.getBdVideo()){
        if(v.getArquivo().getDataCriacao().equals(data)){
            modelVid.insertRow(posVid, new Object[]{
                v.getId(), v.getTitulo(), v.getDuracao(), v.getArquivo().getExtensao(), 
                v.getArquivo().getTamanhoArquivo(), v.getArquivo().getDataCriacao(), 
                v.getQualidade(), v.getFps(), v.getCodec(), String.format("%.2f", v.calcularMegapixel())
            });
            posVid++;
        }
    }

    if(posFoto == 0 && posMus == 0 && posVid == 0){
        JOptionPane.showMessageDialog(
            this,
            "Nenhuma midia encontrada para a data informada.",
            "Pesquisa",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
}
    
    public void constTabFoto(){
        DefaultTableModel modelTab = (DefaultTableModel) tabFoto.getModel();
        int posLin = 0;
        modelTab.setRowCount(posLin);
        
        for(Foto f : gm.getBdFoto()){
            modelTab.insertRow(posLin, new Object[]{
                f.getId(), f.getTitulo(), f.getArquivo().getExtensao(), 
                f.getArquivo().getTamanhoArquivo(), f.getArquivo().getDataCriacao(),
                f.getAlturaPixel(), f.getLarguraPixel(), f.getModeloCamera(), 
                String.format("%.2f", Double.valueOf(f.calcularMegapixel()))
            });
            posLin++;
        }
    }
    
    public void constTabMusica(){
        DefaultTableModel modelTab = (DefaultTableModel) tabMusica.getModel();
        int posLin = 0;
        modelTab.setRowCount(posLin);
        
        for(Musica m : gm.getBdMusica()){
            modelTab.insertRow(posLin, new Object[]{
                m.getId(), m.getTitulo(), m.getDuracao(), m.getArquivo().getExtensao(), 
                m.getArquivo().getTamanhoArquivo(), m.getArquivo().getDataCriacao(), 
                m.getArtista(), m.getAlbum(), m.getGenero()
            });
            posLin++;
        }
    }
    
    public void constTabVideo(){
        DefaultTableModel modelTab = (DefaultTableModel) tabVideo.getModel();
        int posLin = 0;
        modelTab.setRowCount(posLin);
        
        for(Video v : gm.getBdVideo()){
            modelTab.insertRow(posLin, new Object[]{
                v.getId(), v.getTitulo(), v.getDuracao(), v.getArquivo().getExtensao(), 
                v.getArquivo().getTamanhoArquivo(), v.getArquivo().getDataCriacao(), 
                v.getQualidade(), v.getFps(), v.getCodec(), String.format("%.2f", v.calcularMegapixel())
            });
            posLin++;
        }
    }
    
    public void selectTabFoto(){
        String valLin = "";
        int posLin = tabFoto.getSelectedRow();
        
        for(int col = 0; col < tabFoto.getColumnCount(); col++){
            valLin += tabFoto.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tabFoto.getColumnCount()){
                valLin += " -  ";
            }
        }
        JOptionPane.showMessageDialog(
            this,
            "Midia selecionada:\n" + valLin,
            "Seleção em Tabela",
            1
        );
    }
    
    public void selectTabMusica(){
        String valLin = "";
        int posLin = tabMusica.getSelectedRow();
        
        for(int col = 0; col < tabMusica.getColumnCount(); col++){
            valLin += tabMusica.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tabMusica.getColumnCount()){
                valLin += " -  ";
            }
        }
        JOptionPane.showMessageDialog(
            this,
            "Midia selecionada:\n" + valLin,
            "Seleção em Tabela",
            1
        );
    }
    
    public void selectTabVideo(){
        String valLin = "";
        int posLin = tabVideo.getSelectedRow();
        
        for(int col = 0; col < tabVideo.getColumnCount(); col++){
            valLin += tabVideo.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tabVideo.getColumnCount()){
                valLin += " -  ";
            }
        }
        JOptionPane.showMessageDialog(
            this,
            "Midia selecionada:\n" + valLin,
            "Seleção em Tabela",
            1
        );
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormRelGerMidia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btMostrarTudo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxData;
    private javax.swing.JLabel rotConsulta;
    private javax.swing.JLabel rotFoto;
    private javax.swing.JLabel rotMusica;
    private javax.swing.JLabel rotRelGelMidia;
    private javax.swing.JLabel rotVideo;
    private javax.swing.JScrollPane scrollTabFoto;
    private javax.swing.JScrollPane scrollTabMusica;
    private javax.swing.JScrollPane scrollTabVideo;
    private javax.swing.JTable tabFoto;
    private javax.swing.JTable tabMusica;
    private javax.swing.JTable tabVideo;
    // End of variables declaration//GEN-END:variables
}
