// Apache NetBeans IDE 30

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class FormPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrincipal.class.getName());

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotPrinc = new javax.swing.JLabel();
        rotProjeto = new javax.swing.JLabel();
        barMenuPrinc = new javax.swing.JMenuBar();
        mnIniciar = new javax.swing.JMenu();
        itMnCadFoto = new javax.swing.JMenuItem();
        itMnCadMusica = new javax.swing.JMenuItem();
        itMnCadVideo = new javax.swing.JMenuItem();
        LinSeparador = new javax.swing.JPopupMenu.Separator();
        itMnSair = new javax.swing.JMenuItem();
        mnRelatorio = new javax.swing.JMenu();
        itMnRelGerMidias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Arquivos Multimidia");

        rotPrinc.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        rotPrinc.setText("Janela Principal:");

        rotProjeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rotProjeto.setText("Sistema de Controle de Arquivos Multimidia");

        mnIniciar.setText("Inicio");

        itMnCadFoto.setText("Cadastrar Foto...");
        itMnCadFoto.addActionListener(this::itMnCadFotoActionPerformed);
        mnIniciar.add(itMnCadFoto);

        itMnCadMusica.setText("Cadastrar Musica...");
        itMnCadMusica.addActionListener(this::itMnCadMusicaActionPerformed);
        mnIniciar.add(itMnCadMusica);

        itMnCadVideo.setText("Cadastrar Video...");
        itMnCadVideo.addActionListener(this::itMnCadVideoActionPerformed);
        mnIniciar.add(itMnCadVideo);
        mnIniciar.add(LinSeparador);

        itMnSair.setText("Sair");
        itMnSair.addActionListener(this::itMnSairActionPerformed);
        mnIniciar.add(itMnSair);

        barMenuPrinc.add(mnIniciar);

        mnRelatorio.setText("Relatorio");

        itMnRelGerMidias.setText("Relatorio Geral de Midias...");
        itMnRelGerMidias.addActionListener(this::itMnRelGerMidiasActionPerformed);
        mnRelatorio.add(itMnRelGerMidias);

        barMenuPrinc.add(mnRelatorio);

        setJMenuBar(barMenuPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rotProjeto)
                    .addComponent(rotPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rotPrinc)
                .addGap(18, 18, 18)
                .addComponent(rotProjeto)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnCadFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFotoActionPerformed
        abreCadFoto();
    }//GEN-LAST:event_itMnCadFotoActionPerformed

    private void itMnCadMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMusicaActionPerformed
        abreCadMusica();
    }//GEN-LAST:event_itMnCadMusicaActionPerformed

    private void itMnCadVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadVideoActionPerformed
        abreCadVideo();
    }//GEN-LAST:event_itMnCadVideoActionPerformed

    private void itMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSairActionPerformed
        sair();
    }//GEN-LAST:event_itMnSairActionPerformed

    private void itMnRelGerMidiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelGerMidiasActionPerformed
        abreRelGerMidias();
    }//GEN-LAST:event_itMnRelGerMidiasActionPerformed

    public void abreCadFoto(){
        FormCadFoto.geraCadFoto().setVisible(true);
    }
    
    public void abreCadMusica(){
        FormCadMusica.geraCadMus().setVisible(true);
    }
    
    public void abreCadVideo(){
        FormCadVideo.geraCadVid().setVisible(true);
    }
    
    public void abreRelGerMidias(){
        FormRelGerMidia.geraRelatGeral().setVisible(true);
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saida do Sistema",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator LinSeparador;
    private javax.swing.JMenuBar barMenuPrinc;
    private javax.swing.JMenuItem itMnCadFoto;
    private javax.swing.JMenuItem itMnCadMusica;
    private javax.swing.JMenuItem itMnCadVideo;
    private javax.swing.JMenuItem itMnRelGerMidias;
    private javax.swing.JMenuItem itMnSair;
    private javax.swing.JMenu mnIniciar;
    private javax.swing.JMenu mnRelatorio;
    private javax.swing.JLabel rotPrinc;
    private javax.swing.JLabel rotProjeto;
    // End of variables declaration//GEN-END:variables
}
