import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class FormCadVideo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadVideo.class.getName());

    private Video video = new Video();
    private BDMidia gm = BDMidia.geraBDMidia();
    
    private static FormCadVideo cadVideoUnico;
    
    private FormCadVideo() {
        initComponents();
    }
    
    // METODO SINGLETON
    public static FormCadVideo geraCadVid(){
        if(cadVideoUnico == null){
            cadVideoUnico = new FormCadVideo();
        }
        return cadVideoUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotID = new javax.swing.JLabel();
        rotTitulo = new javax.swing.JLabel();
        rotDuracao = new javax.swing.JLabel();
        rotExtensao = new javax.swing.JLabel();
        rotTamArq = new javax.swing.JLabel();
        rotDataCriacao = new javax.swing.JLabel();
        rotQualidade = new javax.swing.JLabel();
        rotQualidade2 = new javax.swing.JLabel();
        rotFPS = new javax.swing.JLabel();
        rotCodec = new javax.swing.JLabel();
        cxId = new javax.swing.JTextField();
        cxTitulo = new javax.swing.JTextField();
        cxDuracao = new javax.swing.JTextField();
        cxExtensao = new javax.swing.JTextField();
        cxTamArq = new javax.swing.JTextField();
        cxDataCriacao = new javax.swing.JTextField();
        cxQualidade = new javax.swing.JTextField();
        cxFps = new javax.swing.JTextField();
        cxCodec = new javax.swing.JTextField();
        btInserirMidia = new javax.swing.JButton();
        btAtualizaVideo = new javax.swing.JButton();
        btConsVideo = new javax.swing.JButton();
        btRemoveMidia = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        scrollTabVideo = new javax.swing.JScrollPane();
        tabVideo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Video");

        rotID.setText("ID:");

        rotTitulo.setText("Titulo:");

        rotDuracao.setText("Duracao:");

        rotExtensao.setText("Extensao:");

        rotTamArq.setText("Tamanho do Arquivo:");

        rotDataCriacao.setText("Data de Criacao:");

        rotQualidade.setText("Qualidade:");

        rotQualidade2.setForeground(new java.awt.Color(102, 102, 102));
        rotQualidade2.setText("(SD/HD/FULL HD/4K)");

        rotFPS.setText("FPS:");

        rotCodec.setText("Codec:");

        btInserirMidia.setText("Inserir");
        btInserirMidia.addActionListener(this::btInserirMidiaActionPerformed);

        btAtualizaVideo.setText("Atualizar Video");
        btAtualizaVideo.addActionListener(this::btAtualizaVideoActionPerformed);

        btConsVideo.setText("Consultar Video");
        btConsVideo.addActionListener(this::btConsVideoActionPerformed);

        btRemoveMidia.setText("Remover Midia");
        btRemoveMidia.addActionListener(this::btRemoveMidiaActionPerformed);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(this::btLimparActionPerformed);

        btSair.setText("Sair");
        btSair.addActionListener(this::btSairActionPerformed);

        tabVideo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Qualidade", "FPS", "Extensao", "Duracao", "Data", "MP"
            }
        ));
        tabVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVideoMouseClicked(evt);
            }
        });
        scrollTabVideo.setViewportView(tabVideo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrollTabVideo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rotTamArq, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cxTamArq))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rotExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cxExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rotDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rotTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rotID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cxTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rotQualidade, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rotQualidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cxQualidade, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rotFPS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rotCodec, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cxCodec, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cxFps, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rotDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cxDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btInserirMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btAtualizaVideo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btConsVideo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btRemoveMidia))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotID)
                            .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotDataCriacao)
                            .addComponent(cxDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotTitulo)
                            .addComponent(cxTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotQualidade2))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotDuracao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotExtensao)
                            .addComponent(cxExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotTamArq)
                            .addComponent(cxTamArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxQualidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rotQualidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotFPS)
                            .addComponent(cxFps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotCodec)
                            .addComponent(cxCodec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserirMidia)
                    .addComponent(btAtualizaVideo)
                    .addComponent(btConsVideo)
                    .addComponent(btRemoveMidia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTabVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btInserirMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirMidiaActionPerformed
        insMidia();
        constTab();
    }//GEN-LAST:event_btInserirMidiaActionPerformed

    private void btAtualizaVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaVideoActionPerformed
        atualizaVideo();
        constTab();
    }//GEN-LAST:event_btAtualizaVideoActionPerformed

    private void btConsVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsVideoActionPerformed
        consVideoId();
    }//GEN-LAST:event_btConsVideoActionPerformed

    private void btRemoveMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveMidiaActionPerformed
        removeMidiaId();
        constTab();
    }//GEN-LAST:event_btRemoveMidiaActionPerformed

    private void tabVideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVideoMouseClicked
        selectTabVideo();
    }//GEN-LAST:event_tabVideoMouseClicked

    public void limpar(){
        cxId.setText("");
        cxTitulo.setText("");
        cxDuracao.setText("");
        cxExtensao.setText("");
        cxTamArq.setText("");
        cxDataCriacao.setText("");
        cxQualidade.setText("");
        cxFps.setText("");
        cxCodec.setText("");
        cxId.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            dispose();
        }
    }
    
    public void selectTabVideo(){
        String valLin = "";
        int posLin = tabVideo.getSelectedRow();
        
        for(int col = 0; col < tabVideo.getColumnCount(); col++){
            valLin += tabVideo.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tabVideo.getColumnCount()){
                valLin += " -  ";
            }
        }
        JOptionPane.showMessageDialog(
            this,
            "Midia selecionada:\n" + valLin,
            "Seleção em Tabela",
            1
        );
    }
    
    public void constTab(){
        DefaultTableModel modelTab = (DefaultTableModel) tabVideo.getModel();
        int posLin = 0;
        modelTab.setRowCount(posLin);
        
        for(Video v : gm.getBdVideo()){
            modelTab.insertRow(posLin, new Object[]{
                v.getId(), v.getTitulo(), v.getQualidade(), v.getFps(), v.getArquivo().getExtensao(), 
                v.getDuracao(), v.getArquivo().getDataCriacao(), String.format("%.2f", v.calcularMegapixel())
            });
            posLin++;
        }
    }
    
    public void insMidia(){
        video = new Video();
        int erro = 0;
        
        try {
            video.setId(Integer.parseInt(cxId.getText()));
            video.setTitulo(cxTitulo.getText());
            video.setDuracao(Integer.parseInt(cxDuracao.getText()));
            video.getArquivo().setExtensao(cxExtensao.getText()); 
            video.getArquivo().setTamanhoArquivo(Float.parseFloat(cxTamArq.getText())); 
            video.getArquivo().setDataCriacao(cxDataCriacao.getText()); 
            video.setQualidade(cxQualidade.getText());
            video.setFps(Integer.parseInt(cxFps.getText()));
            video.setCodec(cxCodec.getText()); 
            
            if(erro == 0 && video.getId() > 0){
                video = gm.insMidia(video);
            } else {
                video = null;
            }
        
            if(video != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Video inserido com sucesso!",
                    "Inserir Video",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel inserir: Ja existe um video com esse ID",
                    "Inserir Video",
                    JOptionPane.ERROR_MESSAGE   
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }
        catch(DuracaoInvalidaException die){
            JOptionPane.showMessageDialog(
                this,
                "O tempo de duracao do video deve ser maior que 0 segundos",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxDuracao.setText("");
            cxDuracao.requestFocus();
            erro = 1;
        }
        
        catch(TamanhoInvalidoException tie){
            JOptionPane.showMessageDialog(
                this,
                "O tamanho do arquivo deve ser maior que 0 MB",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxTamArq.setText("");
            cxTamArq.requestFocus();
            erro = 1;
        }
        
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "Os campos ID, Duracao, Tamanho e FPS devem conter apenas numeros",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
    }
    
    public void atualizaVideo(){
        video = new Video();
        int erro = 0;
        
        try{
            video.setId(Integer.parseInt(cxId.getText()));
            video.setTitulo(cxTitulo.getText());
            video.setDuracao(Integer.parseInt(cxDuracao.getText()));
            video.getArquivo().setExtensao(cxExtensao.getText()); 
            video.getArquivo().setTamanhoArquivo(Float.parseFloat(cxTamArq.getText())); 
            video.getArquivo().setDataCriacao(cxDataCriacao.getText()); 
            video.setQualidade(cxQualidade.getText());
            video.setFps(Integer.parseInt(cxFps.getText()));
            video.setCodec(cxCodec.getText());
        }
        catch(DuracaoInvalidaException die){
            JOptionPane.showMessageDialog(
                this,
                "O tempo de duracao do video deve ser maior que 0 segundos",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxDuracao.setText("");
            cxDuracao.requestFocus();
            erro = 1;
        }
        
        catch(TamanhoInvalidoException tie){
            JOptionPane.showMessageDialog(
                this,
                "O tamanho do arquivo deve ser maior que 0 MB",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxTamArq.setText("");
            cxTamArq.requestFocus();
            erro = 1;
        }
    
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "Os campos ID, Duracao, Tamanho e FPS devem conter apenas numeros",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
        
        if(erro == 0){
            Video atualizado = gm.atualizaMidia(video);
            if(atualizado != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Video atualizado com sucesso. Verifique os Dados",
                    "Atualização de Midia",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel atualizar: Nao existe um video com este ID",
                    "Atualização de Midia",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        } 
    }
    
    public void consVideoId(){
        video = new Video();
        try{
            video.setId(Integer.parseInt(cxId.getText()));
            
            video = gm.consMidiaId(video);
            
            if(video != null){
                cxId.setText(Integer.toString(video.getId()));
                cxTitulo.setText(video.getTitulo());
                cxDuracao.setText(Integer.toString(video.getDuracao()));
                cxExtensao.setText(video.getArquivo().getExtensao()); 
                cxTamArq.setText(Float.toString(video.getArquivo().getTamanhoArquivo())); 
                cxDataCriacao.setText(video.getArquivo().getDataCriacao()); 
                cxQualidade.setText(video.getQualidade());
                cxFps.setText(Integer.toString(video.getFps()));
                cxCodec.setText(video.getCodec());
                
                JOptionPane.showMessageDialog(
                    this,
                    "Video encontrado. Verifique os Dados",
                    "Consulta de Video",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
            else{
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel realizar a consulta: ID nao encontrado",
                    "Consulta de Video",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }

        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "A entrada de dados deve ser numero",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
        } 
    }
    
    public void removeMidiaId(){
        video = new Video();
        int erro = 0;
        
        try{
            video.setId(Integer.parseInt(cxId.getText()));
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "A entrada de dados deve ser numero",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
        
        if(erro == 0){
            Video removido = gm.removeMidiaId(video);
            
            if(removido != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Video removido com sucesso",
                    "Remover Midia",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel remover: ID nao encontrado",
                    "Remover Midia",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadVideo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizaVideo;
    private javax.swing.JButton btConsVideo;
    private javax.swing.JButton btInserirMidia;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemoveMidia;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxCodec;
    private javax.swing.JTextField cxDataCriacao;
    private javax.swing.JTextField cxDuracao;
    private javax.swing.JTextField cxExtensao;
    private javax.swing.JTextField cxFps;
    private javax.swing.JTextField cxId;
    private javax.swing.JTextField cxQualidade;
    private javax.swing.JTextField cxTamArq;
    private javax.swing.JTextField cxTitulo;
    private javax.swing.JLabel rotCodec;
    private javax.swing.JLabel rotDataCriacao;
    private javax.swing.JLabel rotDuracao;
    private javax.swing.JLabel rotExtensao;
    private javax.swing.JLabel rotFPS;
    private javax.swing.JLabel rotID;
    private javax.swing.JLabel rotQualidade;
    private javax.swing.JLabel rotQualidade2;
    private javax.swing.JLabel rotTamArq;
    private javax.swing.JLabel rotTitulo;
    private javax.swing.JScrollPane scrollTabVideo;
    private javax.swing.JTable tabVideo;
    // End of variables declaration//GEN-END:variables
}
