import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class FormCadMusica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadMusica.class.getName());

    private Musica musica = new Musica();
    private BDMidia gm = BDMidia.geraBDMidia();
    
    private static FormCadMusica cadMusicaUnico;
    
    private FormCadMusica() {
        initComponents();
    }
    
    // METODO SINGLETON
    public static FormCadMusica geraCadMus(){
        if(cadMusicaUnico == null){
            cadMusicaUnico = new FormCadMusica();
        }
        return cadMusicaUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rotID = new javax.swing.JLabel();
        rotTitulo = new javax.swing.JLabel();
        rotDuracao = new javax.swing.JLabel();
        rotExtensao = new javax.swing.JLabel();
        rotTamArq = new javax.swing.JLabel();
        rotDataCriacao = new javax.swing.JLabel();
        rotArtista = new javax.swing.JLabel();
        rotAlbum = new javax.swing.JLabel();
        rotGenero = new javax.swing.JLabel();
        cxId = new javax.swing.JTextField();
        cxTitulo = new javax.swing.JTextField();
        cxDuracao = new javax.swing.JTextField();
        cxExtensao = new javax.swing.JTextField();
        cxTamArq = new javax.swing.JTextField();
        cxDataCriacao = new javax.swing.JTextField();
        cxArtista = new javax.swing.JTextField();
        cxAlbum = new javax.swing.JTextField();
        cxGenero = new javax.swing.JTextField();
        btInserirMidia = new javax.swing.JButton();
        btAtualizaMusica = new javax.swing.JButton();
        btConsMusica = new javax.swing.JButton();
        btRemoveMidia = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        scrollTabMusica = new javax.swing.JScrollPane();
        tabMusica = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Musica");

        rotID.setText("ID:");

        rotTitulo.setText("Titulo:");

        rotDuracao.setText("Duracao:");

        rotExtensao.setText("Extensao:");

        rotTamArq.setText("Tamanho do Arquivo:");

        rotDataCriacao.setText("Data de Criacao:");

        rotArtista.setText("Artista:");

        rotAlbum.setText("Album:");

        rotGenero.setText("Genero:");

        btInserirMidia.setText("Inserir");
        btInserirMidia.addActionListener(this::btInserirMidiaActionPerformed);

        btAtualizaMusica.setText("Atualizar Musica");
        btAtualizaMusica.addActionListener(this::btAtualizaMusicaActionPerformed);

        btConsMusica.setText("Consultar Musica");
        btConsMusica.addActionListener(this::btConsMusicaActionPerformed);

        btRemoveMidia.setText("Remover Midia");
        btRemoveMidia.addActionListener(this::btRemoveMidiaActionPerformed);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(this::btLimparActionPerformed);

        btSair.setText("Sair");
        btSair.addActionListener(this::btSairActionPerformed);

        tabMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Titulo", "Artista", "Album", "Duracao", "Data", "Extensao"
            }
        ));
        tabMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMusicaMouseClicked(evt);
            }
        });
        scrollTabMusica.setViewportView(tabMusica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rotTamArq, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxTamArq))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rotExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cxExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rotDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rotTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(rotID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(23, 23, 23)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cxTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rotDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cxDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(rotArtista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rotAlbum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(rotGenero, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cxArtista)
                                            .addComponent(cxAlbum)
                                            .addComponent(cxGenero)))))
                            .addComponent(scrollTabMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btInserirMidia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAtualizaMusica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btConsMusica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRemoveMidia)))
                        .addContainerGap(42, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotID)
                    .addComponent(cxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotDataCriacao)
                    .addComponent(cxDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotTitulo)
                    .addComponent(cxTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotArtista)
                    .addComponent(cxArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotDuracao)
                    .addComponent(rotAlbum)
                    .addComponent(cxAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotExtensao)
                    .addComponent(cxExtensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rotGenero)
                    .addComponent(cxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rotTamArq)
                    .addComponent(cxTamArq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserirMidia)
                    .addComponent(btAtualizaMusica)
                    .addComponent(btConsMusica)
                    .addComponent(btRemoveMidia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTabMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInserirMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirMidiaActionPerformed
        insMidia();
        constTab();
    }//GEN-LAST:event_btInserirMidiaActionPerformed

    private void btAtualizaMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizaMusicaActionPerformed
        atualizaMusica();
        constTab();
    }//GEN-LAST:event_btAtualizaMusicaActionPerformed

    private void btConsMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsMusicaActionPerformed
        consMusicaId();
    }//GEN-LAST:event_btConsMusicaActionPerformed

    private void btRemoveMidiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveMidiaActionPerformed
        removeMidiaId();
        constTab();
    }//GEN-LAST:event_btRemoveMidiaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void tabMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMusicaMouseClicked
        selectTabMusica();
    }//GEN-LAST:event_tabMusicaMouseClicked

    public void limpar(){
        cxId.setText("");
        cxTitulo.setText("");
        cxDuracao.setText("");
        cxExtensao.setText("");
        cxTamArq.setText("");
        cxDataCriacao.setText("");
        cxArtista.setText("");
        cxAlbum.setText("");
        cxGenero.setText("");
        cxId.requestFocus();
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        
        if(resp == 0){
            dispose();
        }
    }
    
    public void selectTabMusica(){
        String valLin = "";
        int posLin = tabMusica.getSelectedRow();
        
        for(int col = 0; col < tabMusica.getColumnCount(); col++){
            valLin += tabMusica.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tabMusica.getColumnCount()){
                valLin += " -  ";
            }
        }
        JOptionPane.showMessageDialog(
            this,
            "Midia selecionada:\n" + valLin,
            "Seleção em Tabela",
            1
        );
    }
    
    public void constTab(){
        DefaultTableModel modelTab = (DefaultTableModel) tabMusica.getModel();
        int posLin = 0;
        modelTab.setRowCount(posLin);
        
        for(Musica m : gm.getBdMusica()){
            modelTab.insertRow(posLin, new Object[]{
                m.getId(), m.getTitulo(), m.getArtista(), m.getAlbum(), m.getDuracao(), 
                m.getArquivo().getDataCriacao(), m.getArquivo().getExtensao()
            });
            posLin++;
        }
    }
    
    public void insMidia(){
        musica = new Musica();
        int erro = 0;
        
        try {
            musica.setId(Integer.parseInt(cxId.getText()));
            musica.setTitulo(cxTitulo.getText());
            musica.setDuracao(Integer.parseInt(cxDuracao.getText()));
            musica.getArquivo().setExtensao(cxExtensao.getText()); 
            musica.getArquivo().setTamanhoArquivo(Float.parseFloat(cxTamArq.getText())); 
            musica.getArquivo().setDataCriacao(cxDataCriacao.getText()); 
            musica.setArtista(cxArtista.getText());
            musica.setAlbum(cxAlbum.getText());
            musica.setGenero(cxGenero.getText()); 
            
            if(erro == 0 && musica.getId() > 0){
                musica = gm.insMidia(musica);
            } else {
                musica = null;
            }
        
            if(musica != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Musica inserida com sucesso!",
                    "Inserir Musica",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel inserir: Ja existe uma musica com esse ID",
                    "Inserir Musica",
                    JOptionPane.ERROR_MESSAGE   
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }
        catch(DuracaoInvalidaException die){
            JOptionPane.showMessageDialog(
                this,
                "O tempo de duracao da musica deve ser maior que 0 segundos",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxDuracao.setText("");
            cxDuracao.requestFocus();
            erro = 1;
        }
        
        catch(TamanhoInvalidoException tie){
            JOptionPane.showMessageDialog(
                this,
                "O tamanho do arquivo deve ser maior que 0 MB",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxTamArq.setText("");
            cxTamArq.requestFocus();
            erro = 1;
        }
        
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "Os campos ID, Duracao e Tamanho devem conter apenas numeros",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
    }
    
    public void atualizaMusica(){
        musica = new Musica();
        int erro = 0;
        
        try{
            musica.setId(Integer.parseInt(cxId.getText()));
            musica.setTitulo(cxTitulo.getText());
            musica.setDuracao(Integer.parseInt(cxDuracao.getText()));
            musica.getArquivo().setExtensao(cxExtensao.getText()); 
            musica.getArquivo().setTamanhoArquivo(Float.parseFloat(cxTamArq.getText())); 
            musica.getArquivo().setDataCriacao(cxDataCriacao.getText()); 
            musica.setArtista(cxArtista.getText());
            musica.setAlbum(cxAlbum.getText());
            musica.setGenero(cxGenero.getText());
        }
        catch(DuracaoInvalidaException die){
            JOptionPane.showMessageDialog(
                this,
                "O tempo de duracao da musica deve ser maior que 0 segundos",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxDuracao.setText("");
            cxDuracao.requestFocus();
            erro = 1;
        }
        
        catch(TamanhoInvalidoException tie){
            JOptionPane.showMessageDialog(
                this,
                "O tamanho do arquivo deve ser maior que 0 MB",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxTamArq.setText("");
            cxTamArq.requestFocus();
            erro = 1;
        }
    
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "Os campos ID, Duracao e Tamanho devem conter apenas numeros",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
        
        if(erro == 0){
            Musica atualizado = gm.atualizaMidia(musica);
            if(atualizado != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Musica atualizada com sucesso. Verifique os Dados",
                    "Atualização de Midia",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel atualizar: Nao existe uma musica com este ID",
                    "Atualização de Midia",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        } 
    }
    
    public void consMusicaId(){
        musica = new Musica();
        try{
            musica.setId(Integer.parseInt(cxId.getText()));
            
            musica = gm.consMidiaId(musica);
            
            if(musica != null){
                cxId.setText(Integer.toString(musica.getId()));
                cxTitulo.setText(musica.getTitulo());
                cxDuracao.setText(Integer.toString(musica.getDuracao()));
                cxExtensao.setText(musica.getArquivo().getExtensao()); 
                cxTamArq.setText(Float.toString(musica.getArquivo().getTamanhoArquivo())); 
                cxDataCriacao.setText(musica.getArquivo().getDataCriacao()); 
                cxArtista.setText(musica.getArtista());
                cxAlbum.setText(musica.getAlbum());
                cxGenero.setText(musica.getGenero());
                
                JOptionPane.showMessageDialog(
                    this,
                    "Musica encontrada. Verifique os Dados",
                    "Consulta de Musica",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
            else{
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel realizar a consulta: ID nao encontrado",
                    "Consulta de Musica",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }

        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "A entrada de dados deve ser numero",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
        } 
    }
    
    public void removeMidiaId(){
        musica = new Musica();
        int erro = 0;
        
        try{
            musica.setId(Integer.parseInt(cxId.getText()));
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                this,
                "A entrada de dados deve ser numero",
                "Erro",
                JOptionPane.ERROR_MESSAGE
            );
            cxId.setText("");
            cxId.requestFocus();
            erro = 1;
        }
        
        if(erro == 0){
            Musica removido = gm.removeMidiaId(musica);
            
            if(removido != null){
                JOptionPane.showMessageDialog(
                    this,
                    "Musica removida com sucesso",
                    "Remover Midia",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limpar();
            } else {
                JOptionPane.showMessageDialog(
                    this,
                    "Nao foi possivel remover: ID nao encontrado",
                    "Remover Midia",
                    JOptionPane.ERROR_MESSAGE
                );
                cxId.setText("");
                cxId.requestFocus();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadMusica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizaMusica;
    private javax.swing.JButton btConsMusica;
    private javax.swing.JButton btInserirMidia;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemoveMidia;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField cxAlbum;
    private javax.swing.JTextField cxArtista;
    private javax.swing.JTextField cxDataCriacao;
    private javax.swing.JTextField cxDuracao;
    private javax.swing.JTextField cxExtensao;
    private javax.swing.JTextField cxGenero;
    private javax.swing.JTextField cxId;
    private javax.swing.JTextField cxTamArq;
    private javax.swing.JTextField cxTitulo;
    private javax.swing.JLabel rotAlbum;
    private javax.swing.JLabel rotArtista;
    private javax.swing.JLabel rotDataCriacao;
    private javax.swing.JLabel rotDuracao;
    private javax.swing.JLabel rotExtensao;
    private javax.swing.JLabel rotGenero;
    private javax.swing.JLabel rotID;
    private javax.swing.JLabel rotTamArq;
    private javax.swing.JLabel rotTitulo;
    private javax.swing.JScrollPane scrollTabMusica;
    private javax.swing.JTable tabMusica;
    // End of variables declaration//GEN-END:variables
}
